version: "2"
services:
  db:
    image: mysql:5.7.30 # https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "uttn"
      MYSQL_ROOT_PASSWORD: 63eaQB9wtLqmNBpg
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "yarn dev"
