prisma:
	## Criacao de Migracoes de Base de Dados
	npx prisma migrate dev

	## execucao de alteracoes prisma - db 
	npx prisma db pull

	## execucao de alteracoes db - prisma
	npx prisma db push
	
	## execucao do seed
	npx prisma db seed

	## Visualizacao grafica
	npx prisma studio

	## Dababase em Produção
	npx prisma generate